### PR TITLE
#5 create more convenient interface

### PR DESCRIPTION
**Pull request by Alkhimovmv**
1. Made responsive layout
desktopLAyout
ipadProLayout
iphone7layout
iphone5Layout
2. Update main page: added sections Experienced & Professional Team and About project
mainPage
3. More convenient input for user's answer
input
4. New header(added link on github(for test), then new links will be added; when you click on the logo, you go to the main page)

### CODE REVIEW

**Comment by AlexKay28** [comment]
cool! I like it
but maybe it would be cool also to color up answers? it just may help user to recognize where are his own and correct answer

Screenshot_20210927_150051

I would list my thoughts like this:
1. One single color for all three service words (grey for example)
2. Different colors for answer, question, and user answer (smth like this for example)
Screenshot_20210927_150307

**Comment by Alkhimovmv** [comment]
Good idea. I will do it soon

**Comment by Alkhimovmv** [comment]
Done. The answer remains white for now, but it is assumed that later it will have a color in accordance with whether the answer was entered correctly.
newColor

**Comment by AlexKay28** [comment]
Awesome! a lot more comfortable to see)

**Comment by AlexKay28** [comment]
@Alkhimovmv 
yeah, about the correctness of the input answer... there will be shown some corrections
but you remember, there are two ways - or whole answer phrase will be green (too many mistakes) or particular parts of it if there are only 2-3  
Also, it looks like it maybe is shown in a little bit another manner, I guess this discussion is already enough to be separate task defo

**Review by AlexKay28 — APPROVED** [review]

**Review by AlexKay28 — CHANGES_REQUESTED** [review]
resolve conflicts

**Review by AlexKay28 — APPROVED** [review]

**Pull request merged**
