### PR TITLE
75 New design

### PR DESCRIPTION
**Pull request by Alkhimovmv**
I updated the design to match the template. Changing the practice page will be moved into a separate task. As well as adaptation to mobile devices.
Снимок экрана от 2021-12-26 01-16-25
Снимок экрана от 2021-12-26 01-16-39
Снимок экрана от 2021-12-26 01-15-57
Снимок экрана от 2021-12-26 01-17-04
Снимок экрана от 2021-12-26 01-17-17
Снимок экрана от 2021-12-26 01-19-00

### CODE REVIEW

**Comment by Alkhimovmv** [comment]
[Make a new design](https://trello.com/c/gU1E1Eka/19-make-a-new-design)

**Comment by AlexKay28** [comment]
@Alkhimovmv 
look good! 
do we already have English-French or Russian-English buttons frozen if we switch asked languages order?

**Review by AlexKay28 — APPROVED** [review]

**Review by AlexKay28 — APPROVED** [review]

**Comment by Alkhimovmv** [comment]
> 

@AlexKay28 yes

**Comment by Alkhimovmv** [comment]
I redesign question page
Снимок экрана от 2022-01-18 21-59-28
Снимок экрана от 2022-01-18 22-13-48

**Comment by AlexKay28** [comment]
@Alkhimovmv looks very close to what we wanted. like this
but, maybe instead of "Enter text" inside the input form it would be better to put something like "Translate the sentence", "Enter translation"...?

**Review by AlexKay28 — APPROVED** [review]

**Comment by Alkhimovmv** [comment]
@AlexKay28, I corrected to "Enter translation"
Снимок экрана от 2022-01-19 19-00-05

**Pull request merged**
