### PR TITLE
89 add tips to nlp service

### PR DESCRIPTION
**Pull request by AlexKay28**
Add tips to `nlp_module` service and provide with API to the `/answer` endpoint

### CODE REVIEW

**Comment by AlexKay28** [comment]
Tips are represented as special symbols inside the suggested difference between two text
type of symbols is : https://en.wikipedia.org/wiki/ANSI_escape_code

image

**Comment by AlexKay28** [comment]
@Alkhimovmv if you are OK with such kind of segmentation, then it will be merged to master as it is

**Comment by AlexKay28** [comment]
in this PR simultaneously updated dvc files of DB and changed procedures for phrases uploading

**Comment by Alkhimovmv** [comment]
@AlexKay28, I think that it is ok

**Review by Alkhimovmv — APPROVED** [review]

**Pull request merged**
